module.exports = {
	'D.Va' : 'tank',
	'Orisa' : 'tank',
	'Reinhardt' : 'tank',
	'Roadhog' : 'tank',
	'Winston' : 'tank',
	'Wrecking Ball' : 'tank',
	'Zarya' : 'tank',
	'Ashe' : 'dps',
	'Bastion' : 'dps',
	'Doomfist' : 'dps',
	'Genji' : 'dps',
	'Hanzo' : 'dps',
	'Junkrat' : 'dps',
	'Mccree' : 'dps',
	'Mei' : 'dps',
	'Pharah' : 'dps',
	'Reaper' : 'dps',
	'Soldier: 76' : 'dps',
	'Sombra' : 'dps',
	'Symmetra' : 'dps',
	'Torbjörn' : 'dps',
	'Tracer' : 'dps',
	'Widowmaker' : 'dps',
	'Ana' : 'support',
	'Brigitte' : 'support',
	'Lucio' : 'support',
	'Mercy' : 'support',
	'Moira' : 'support',
	'Zenyatta' : 'support'
}